# Site settings
# source ~/.rvm/scripts/rvm
title: Ramon Barros
description: 'Full Stack Developer'
url: 'http://ramon-barros.com'
baseurl: '/'
google_analytics: 'UA-32626396-1'

author:
  name: 'Ramon Barros'
  email: contato@ramon-barros.com
  twitter_username: ramonbarros_
  github_username:  rbarros
  linkedin_username:  ramonbarros

# Build settings
destination: _site
paginate: 10
#paginate_path: "/page:num/"
#permalink: /:year/:title/
permalink: /:categories/:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
gems: ['jekyll-paginate']
