# Site settings
title: Ramon Barros
description: 'Desenvolvedor'
url: 'http://ramon-barros.com'
baseurl: '/rbarros.github.io/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Ramon Barros'
  email: contato@ramon-barros.com
  twitter_username: ramonbarros_
  github_username:  rbarros
  linkedin_username:  ramonbarros

# Build settings
destination: _site
paginate: 10
#paginate_path: "/page:num/"
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
gems: ['jekyll-paginate']